### ISSUE TITLE
something wrong in obj, mtl and json file when object name contain non-ISO-8859-1 characters

### ISSUE THREAD

**Issue by sonnyyin** [adizanni/ExportToHASS#3]
This  plugin is good 。however， after export obj，mtl，json file use this plugin，there is something wrong in json file，like this

<img width="1122" alt="微信截图_20210909000239" src="https://user-images.githubusercontent.com/33096611/132544900-2aa3a024-4b7c-4213-b9b2-2b5d88afd566.png">

in green box，the same two “window” has the same object id in JSON file；
and in red box，the 3d model Name field with Chinese characters cannot export correctly，in HA ，the model with materials cannot display or display wrong material image.

<img width="624" alt="微信截图_20210909001942" src="https://user-images.githubusercontent.com/33096611/132546933-bd97f63d-c48b-49b5-882e-7194f3c53b26.png">

<img width="746" alt="微信截图_20210909001834" src="https://user-images.githubusercontent.com/33096611/132546964-b74ca3b4-e02e-46df-aea0-cae7437c4e76.png">

Hope solve this problem in future.

**Comment by adizanni** [comment]
Hello Sonny,

I have no control on the uniqueness of the names in Sweethome3d. I cannot see the full name of the objects in your Sweethome3d model but I suggest you change the name with something unique (for my models I append the name of the room to the name of the furniture, etc.).

I did not get if the rug is the object that is not exported correctly because the name is chinese. I must say that I have not a lot of experience with code internazionalization but if you send me your model, I can try to reporduce the issue and fix it.
From your side I've seen that some of the furniture names are already in english, please try to rename all the object to english names as a temporary workaround before I my fix (that may take a while)

**Comment by sonnyyin** [comment]
Thanks for reply. I find that , if i set the software language to chinese in preferences, and the 3D model has chinese translation, after drag the model to canvas，the model name will display the default Chinese translation ，even if i change the model name to English，the export json file also not correct. The model without Chinese translation ，the export file seems right . I will upload my sh3d file soon, you can analysis it for this issue . 
Thanks for you！

[myhome1.zip](https://github.com/adizanni/ExportToHASS/files/7137347/myhome1.zip)

**Comment by adizanni** [comment]
I confirm chinese characters string are not managed properly by the export plugin, files are opened in ISO-8859-1 character set. I can try to support UTF-8 encoding to include Chinese in the supported character set, but I need some time and be sure I'm not breaking other functions. Would you be so kind to apply the workaround (only ISO 8859 characters) in the object names ? I do not think it is a big deal, you have to do it only once and anyway you have already english names in your model......

**Comment by sonnyyin** [comment]
Thanks for your suggestion, i will try it soon.

**Comment by adizanni** [comment]
I have not much time to spend and for the moment I have decided that I will not support other character set than ISO 8859.
