### ISSUE TITLE
Limit of objects?

### ISSUE THREAD

**Issue by 0nikola1** [adizanni/ExportToHASS#4]
Is there some limit of objects to export? I get 1002 objects exported when I try to export

**Comment by adizanni** [comment]
Hello Nikola, I do not get if you have an error or not ? I do not think there Is a limit on the number of objects that can be exported

**Comment by 0nikola1** [comment]
I just can't find object, I add few more object and export again and it still have 1002 lines  in home.json  I will try to check temp files or something

**Comment by 0nikola1** [comment]
It is lights that I am adding, is there something specific with lights, I tried to add a few more after the first one and now all of them are missing, only 1 worked fine

**Comment by 0nikola1** [comment]
I tried again and when I add only lights, even of different colors only 1 of them is exported. So it isn't limit of object but something with lights. Is there a better way to use a light source?
![image](https://user-images.githubusercontent.com/40897274/135224250-e6e098e6-89d3-48b7-afaf-0692b82b6ef7.png)

`{ 
 "Blue_light_source_1" : { "object_id": "Blue_light_source_1" }
}
`

**Comment by adizanni** [comment]
Hello Nikola,  lights sources in Sweethome3d are not used inside the floor3d card. For the card you just need to specify the object that will act as the source of the light (such as a lamp object). I've not tested the export of light sources also because they have no used in the card. I will test it but please try to remove the light source from your model

**Comment by 0nikola1** [comment]
Ok, I will use different object then, it weird to me as If I place 1 light it exports and it works but for multiple it doesn’t
